spring:
  datasource:
    url: jdbc:mysql://springsecurity.cx0mwyo0sktk.us-east-1.rds.amazonaws.com/eazybank
    username: admin
    password: mysqlspringsecurity
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
